/**
 * Text for FooterExtras page.
 *
 * @name footerExtras_text
 * @constant {Object}
 * @memberOf Pages:footerExtras
 * @locus Client
 *
 * @property {Object} header - i18n of {title, lead, body}
 * @property {Object} page - i18n of {page, components, list, form}
 *
 */

//** page header; set to null to not display header or a specific item
export const header = {
    en: {
        title:  "Footer Extras Page",
        subtitle:   "Extras in footer include system messages, gdr and pwa enabler.",
        body:   "",
    }
};

import {generateId} from "../../../Functions/utilities/generateId";
export const page = {
    page: {
        en: {
            systemMessages: "System Messages",
            systemMessagesBody: [
                "<p>This component provides for the display of a message generated by any page, component or by the application.  " +
                "Messages are appended to the <code>$message</code> array in the global Svelte store and will be immediately " +
                "shown at the top right of the viewport.</p>" +
                "<p>A message is an object with the following structure: </p>" +
                "<ul>" +
                "<li><b>id:</b> {string} a unique id per message that is used to manually close the message;</li>" +
                "<li><b>state:</b> {string} one of 'success', 'warning', 'fail', 'add', 'remove' or 'uncertain', sets background colour and icon;</li>" +
                "<li><b>text:</b> {string} message to display;</li>" +
                "<li><b>closable:</b> {boolean} (optional) shows delete button at right top. Default = true;</li>" +
                "<li><b>duration:</b> {number} (optional) milliseconds before message will be cloased. Default = 5000; 0 = never.</li>" +
                "</ul>",
            ],

            gdpr: "General Data Protection Regulation (GDPR)",
            gdprBody: [
                "This component allows you to configure a GDPR notification for your users.",

                "The component has buttons for acceptance, rejection or postponement of the GDPR notification.  " +
                "This component tries to use local storage if available, otherwise browser cookies are used to track the acceptance state. ",

                "Two events are emitted:  'cookie-status' on component initialization that shows stored status; and " +
                "'gdpr-cookie' that shows the clicked button state."
            ],

            pwa: "Progressive Web App Enabler",
            pwaBody: [
                "<p>The PWA component provides two capabilities:</p>" +
                "<ol><li>checks if the browser supports service workers;</li>" +
                "<li>encourages the user to install this website as a progressive web app with an icon on the home page or desktop.</li></ol>"
            ],

            other: "Other Components (future)",
            otherBody: ["Other capabilities that can be included in the footer components include Google tracking, " +
                "Intercom style customer support and Hotjar usage tracking."]
        },
    },

    components: {
        en: {

            messages1: [
                {
                    id: generateId(6),
                    state: "fail",
                    text: "Test 'fail' from footerExtras."
                },

                {
                    id: generateId(6),
                    state: "success",
                    text: "Test 'success' from footerExtras.",
                    closable: false,
                    duration: 10000
                },

                {
                    id: generateId(6),
                    state: "warning",
                    text: "Test 'warning' from footerExtras."
                }
            ],

            messages2: [
                {
                    id: generateId(6),
                    state: "add",
                    text: "Test 'add' from footerExtras.",
                    duration: 9000
                },

                {
                    id: generateId(6),
                    state: "remove",
                    text: "Test 'remove' from footerExtras."
                },

                {
                    id: generateId(6),
                    state: "uncertain",
                    text: "Test 'uncertain' six from footerExtras."
                }
            ],
        }
    }
};

